# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons1.xdc

# Block Designs: bd/design_5/design_5.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_5 || ORIG_REF_NAME==design_5} -quiet] -quiet

# IP: bd/design_5/ip/design_5_processing_system7_0_0/design_5_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_5_processing_system7_0_0 || ORIG_REF_NAME==design_5_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_axi_iic_0_1/design_5_axi_iic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_5_axi_iic_0_1 || ORIG_REF_NAME==design_5_axi_iic_0_1} -quiet] -quiet

# IP: bd/design_5/ip/design_5_axi_smc_0/design_5_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_5_axi_smc_0 || ORIG_REF_NAME==design_5_axi_smc_0} -quiet] -quiet

# IP: bd/design_5/ip/design_5_rst_ps7_0_100M_0/design_5_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_5_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_5_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/Users/291914/project_6/project_6.gen/sources_1/bd/design_5/design_5_ooc.xdc
