domain_path: C:\Users\291914\project_6\workspace2\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\XilinxVitis\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
