# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/291914/project_6/project_6.srcs/sources_1/bd/design_3/ip/design_3_axi_interconnect_0_imp_auto_pc_0/design_3_axi_interconnect_0_imp_auto_pc_0.xci
# IP: The module: 'design_3_axi_interconnect_0_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/291914/project_6/project_6.gen/sources_1/bd/design_3/ip/design_3_axi_interconnect_0_imp_auto_pc_0/design_3_axi_interconnect_0_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_axi_interconnect_0_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/291914/project_6/project_6.srcs/sources_1/bd/design_3/ip/design_3_axi_interconnect_0_imp_auto_pc_0/design_3_axi_interconnect_0_imp_auto_pc_0.xci
# IP: The module: 'design_3_axi_interconnect_0_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/291914/project_6/project_6.gen/sources_1/bd/design_3/ip/design_3_axi_interconnect_0_imp_auto_pc_0/design_3_axi_interconnect_0_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_axi_interconnect_0_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
